### ISSUE TITLE
older version

### ISSUE THREAD

**Issue by Mealoore** [niXman/mingw-builds-binaries#10]
Is there an old version, like 8.1.0 or earlier?

**Comment by niXman** [comment]
no, but I will start building now :)

**Comment by Mealoore** [comment]
> no, but I will start building now :)
> which version exactly?

any version earlier than 9 is ok, thanks a lot

**Comment by niXman** [comment]
in process: https://github.com/niXman/mingw-builds-binaries/actions/runs/2940553931

**Comment by niXman** [comment]
finished.

please close the issue.

**Comment by niXman** [comment]
@Mealoore ping

**Comment by Mealoore** [comment]
> @Mealoore ping

sorry,  I have forgotten it
