### ISSUE TITLE
The installer hangs on Extraction

### ISSUE THREAD

**Issue by su8** [niXman/mingw-builds-binaries#22]
The installer hangs on Extraction. windows 10 64 bit. Tried to install it with win32, something like jiji and not posix standard then after downloading mingw the installer hangs on Extraction.

**Comment by niXman** [comment]
when did you download it?
it was updated yesterday.

**Comment by su8** [comment]
I download it from the last version 12.0.0 from the Releases

**Comment by niXman** [comment]
sorry, I don't understand...

in your first message:
> The installer hangs on Extraction.

but in your next message you say about version 12.0.0 from the Releases:
> 12.0.0 from the Releases

but in the Releases there is no any installers, there is just archives. furthermore, there is no version 12.0.0.

**Comment by su8** [comment]
Yeah I messed it up, downloaded the mingw installer from sourceforge and right now I unzipped the posix archive and it works like a charm. Sorry about it.
