### ISSUE TITLE
gdb not run

### ISSUE THREAD

**Issue by zetab007** [niXman/mingw-builds-binaries#26]
I downloaded this package: [i686-12.2.0-release-win32-sjlj-rt_v10-rev0.7z](https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev0/i686-12.2.0-release-win32-sjlj-rt_v10-rev0.7z)
When I run gdb, an error message pop up saying something like: Unable to find entry point GetSystemTimePreciseAsFileTime in KERNEL32.dll.
I got this error on win7, 64bit system. I have tried on another win10 system, and the gdb works fine.
Does this package support win7?

**Comment by niXman** [comment]
hmm...
according to the doc(https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) the `GetSystemTimePreciseAsFileTime` requires Win8.

you can try to message to the GDB mailing list (gdb@sourceware.org) and ask the developers can the OS version requirements be Win7 at least... maybe there is smth configure options for this...

**Comment by zetab007** [comment]
Found these in gettimeofday.c:

```
# if !(_WIN32_WINNT >= _WIN32_WINNT_WIN8)

/* Avoid warnings from gcc -Wcast-function-type.  */
#  define GetProcAddress \
    (void *) GetProcAddress

/* GetSystemTimePreciseAsFileTime was introduced only in Windows 8.  */
typedef void (WINAPI * GetSystemTimePreciseAsFileTimeFuncType) (FILETIME *lpTime);
static GetSystemTimePreciseAsFileTimeFuncType GetSystemTimePreciseAsFileTimeFunc = NULL;
static BOOL initialized = FALSE;

static void
initialize (void)
{
  HMODULE kernel32 = LoadLibrary ("kernel32.dll");
  if (kernel32 != NULL)
    {
      GetSystemTimePreciseAsFileTimeFunc =
        (GetSystemTimePreciseAsFileTimeFuncType) GetProcAddress (kernel32, "GetSystemTimePreciseAsFileTime");
    }
  initialized = TRUE;
}

# else

#  define GetSystemTimePreciseAsFileTimeFunc GetSystemTimePreciseAsFileTime

# endif
```

Looks like setting _WIN32_WINNT to a lower version when building gdb should make it support OSs older than win8.

**Comment by zetab007** [comment]
I think you can pass the definition through the build script with `--cppflags` option.
For example, 
`./build --cppflags='-D_WIN32_WINNT=0x0601'`
The 0x0601 is the version constant of win7.

**Comment by niXman** [comment]
great!
have you checked that locally? :)

**Comment by niXman** [comment]
moreover, I don't think it is a good idea to pass such option for all the parts of a build...

**Comment by zetab007** [comment]
I tried run the build script without adding the option but failed at the gcc building step.
It may take some time to figure out what happened since it takes hours for my PC to build the whole package.

For not affecting other part of the build, maybe you can modify `/scripts/gdb.sh`.
Adding the definition to the CPPFLAGS setting line, like:
`CPPFLAGS="\"$COMMON_CPPFLAGS\" -D_WIN32_WINNT=0x0601"`

But I think passing it to all parts of the build is reasonable. 
According to the [doc](https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170) _WIN32_WINNT specifies the minimum OS version your code supports. To claim supporting an OS version, every part in the package should support it, not only the gdb.

**Comment by niXman** [comment]
> But I think passing it to all parts of the build is reasonable.
According to the [doc](https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170) _WIN32_WINNT specifies the minimum OS version your code supports. To claim supporting an OS version, every part in the package should support it, not only the gdb.

hmm... lets try.
will modify the Github actions script now, and we can check if the building was finished successfully...

**Comment by niXman** [comment]
hmm...
all the build finished with error code 8 on downloading `expat`...
wtf...

**Comment by zetab007** [comment]
The tarball of expat 2.4.9 was marked vulnerable and renamed.
[https://sourceforge.net/projects/expat/files/expat/2.4.9/](https://sourceforge.net/projects/expat/files/expat/2.4.9/)

**Comment by niXman** [comment]
oh, will update the script now...

**Comment by niXman** [comment]
done. building.

**Comment by niXman** [comment]
@zetab007 it finished.
could you please download and check it?: https://github.com/niXman/mingw-builds/actions/runs/3334721944#artifacts

**Comment by zetab007** [comment]
I still got the GetSystemTimePreciseAsFileTime error, strange...

**Comment by niXman** [comment]
will remove that options from the github actions script for now.
please test it locally first.

**Comment by zetab007** [comment]
ok.

**Comment by niXman** [comment]
@zetab007 look at this: https://github.com/niXman/mingw-builds/pull/621

**Comment by zetab007** [comment]
I'll try the new option locally, see if it can solve the problem.

**Comment by zetab007** [comment]
I can successfully build the package before the merge of new option. 
But after the merge it always fails, even with the same setting as github action.
I followed the steps in README, using MSYS2 MINGW64 shell, and built with following commands:
```
mv /mingw32 /_mingw32
mv /mingw64 /_mingw64
export PATH=/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
cd && git clone https://github.com/niXman/mingw-builds.git
cd && cd mingw-builds
./build --mode=gcc-12.2.0 --jobs=8 --rev=0 --rt-version=v10 --threads=win32 --exceptions=dwarf --arch=i686 --bin-compress --enable-languages=c,c++,fortran
```
It always fails at gcc-12.2.0 building step. Here is the log: [make.zip](https://github.com/niXman/mingw-builds-binaries/files/9895662/make.zip)
What did i do wrong?

**Comment by niXman** [comment]
please re-run the same cmd but with `--jobs=1`, because of multiply building threads the log-file are shuffled. and upload the log again please.

**Comment by niXman** [comment]
no need to clean or remove smth, just re-run the cmd

**Comment by zetab007** [comment]
done. 
[make.zip](https://github.com/niXman/mingw-builds-binaries/files/9895713/make.zip)

**Comment by niXman** [comment]
very strange =)

```cpp
libtool: compile:  /home/zetab/mingw-gcc-12.2.0/i686-1220-win32-dwarf-rt_v10-rev0/build/gcc-12.2.0/./gcc/xgcc -B/home/zetab/mingw-gcc-12.2.0/i686-1220-win32-dwarf-rt_v10-rev0/build/gcc-12.2.0/./gcc/ -L/mingw32/i686-w64-mingw32/lib -L/mingw32/mingw/lib -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/mingw/include -B/mingw32/i686-w64-mingw32/bin/ -B/mingw32/i686-w64-mingw32/lib/ -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/i686-w64-mingw32/sys-include -fno-checking -DHAVE_CONFIG_H -I. -I../../../../../src/gcc-12.2.0/libgomp -I../../../../../src/gcc-12.2.0/libgomp/config/mingw32 -I../../../../../src/gcc-12.2.0/libgomp/config/posix -I../../../../../src/gcc-12.2.0/libgomp -I../../../../../src/gcc-12.2.0/libgomp/../include -pthread -Wall -g -O2 -pipe -fno-ident -I/home/zetab/mingw-gcc-12.2.0/i686-1220-win32-dwarf-rt_v10-rev0/mingw32/opt/include -I/home/zetab/mingw-gcc-12.2.0/prerequisites/i686-zlib-static/include -I/home/zetab/mingw-gcc-12.2.0/prerequisites/i686-w64-mingw32-static/include -MT env.lo -MD -MP -MF .deps/env.Tpo -c ../../../../../src/gcc-12.2.0/libgomp/env.c  -DDLL_EXPORT -DPIC -o .libs/env.o
In file included from ../../../../../src/gcc-12.2.0/libgomp/env.c:34:
./libgomp_f.h:65:10: error: operator '<=' has no left operand
   65 |     && ( <= 8)
      |          ^~
./libgomp_f.h: In function 'omp_check_defines':
./libgomp_f.h:92:18: error: expected expression before '!=' token
   92 |              ||  != __alignof (omp_nest_lock_25_t)
      |                  ^~
```

**Comment by niXman** [comment]
the `libgomp_f.h` file is a generated file from the: https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libgomp/libgomp_f.h.in;h=7063364f53b247d7cbf653dcc97584df6a6dc63d;hb=2ee5e4300186a92ad73f1a1a64cb918dc76c8d67

@zetab007 could you please search in your build tree for the `libgomp_f.h` file and post it here?

**Comment by zetab007** [comment]
[libgomp_f.zip](https://github.com/niXman/mingw-builds-binaries/files/9895823/libgomp_f.zip)

**Comment by zetab007** [comment]
I'll try re-install MSYS2 and rebuild.

**Comment by starg2** [comment]
That's really strange.

@zetab007 btw if you just need binaries built with `--with-default-win32-winnt=0x0601`, you can download them from [my github actions](https://github.com/starg2/mingw-builds/actions/runs/3350177834).

**Comment by zetab007** [comment]
@starg2 Thanks, I'll try your build.
@niXman I found I might mess up my MSYS2 system. Because I renamed /mingw32 and /mingw64 in the beginning, and when the build script startup, it will install packages it need, I found /mingw32 is re-created after the installation.
Do I really need to rename or delete /mingw32 and /mingw64 as README said? I don't see this in the github actions. Or did I miss it?

**Comment by niXman** [comment]
> I found /mingw32 is re-created after the installation.

@zetab007 I think it might have been due to some rules on MSYS2, so it check for the dirs existence...

> Do I really need to rename or delete /mingw32 and /mingw64 as README said?

yes, because the script will check that dirs at startup.
this check was implemented because the building process must install and use its own version of the MinGW-W64 toolchain.

later was added `--provided-toolchain=<path>` options wor the cases when user want to use their version as a local toolchain: https://github.com/niXman/mingw-builds/blob/develop/build#L404 (I didn't notice that no explanation was given)

so, if you want to use your provided toolcain you can use that option and not remove/rename the `mingw32`/`mingw64` dirs.

**Comment by niXman** [comment]
the explanation for the `--provided-toolchain` option: https://github.com/niXman/mingw-builds/pull/581

**Comment by zetab007** [comment]
I set `--provided-toolchain=/`, but got this error:
`Could not execute //mingw32/bin/gcc`

**Comment by niXman** [comment]
because the author of the feature din't think that anyone will use it for FS root =);

https://github.com/niXman/mingw-builds/pull/581/commits/7c0a11cf09371b3bb9fb73e26a14e12aaba61044#diff-3558701b8c27cac1ecec7960864d7350f678ee3336c27a713b866fc65270a80aR927

**Comment by zetab007** [comment]
Ever since I set `--jobs=1`, I never encounter those strange errors anymore. Are there any config must be set before using parallel build?
Another thing, I tried the `--provided-toolchain=<path>` option, using MSYS2's mingw32 toolchain for the building, and the building time became ridiculously long. It took about 30 hours to finish, even though I set the `--jobs=1`, it's still way longer than using the default toolchain.

**Comment by niXman** [comment]
> Ever since I set --jobs=1, I never encounter those strange errors anymore. Are there any config must be set before using parallel build?

what error are you talking about?

> Another thing, I tried the --provided-toolchain=<path> option, using MSYS2's mingw32 toolchain for the building, and the building time became ridiculously long. It took about 30 hours to finish, even though I set the --jobs=1, it's still way longer than using the default toolchain.

very strange... but I have no ideas...

**Comment by zetab007** [comment]
The libgomp_f.h error in my earlier comment, and many other errors. If I enable parallel build, every time I get different error, most of the time there will be some data type undefined and the build process fail at configure step of some part, and sometimes the gcc part will fail at moving gcc to stage1-gcc because of permission denied.

**Comment by niXman** [comment]
have you seen this?: https://github.com/niXman/mingw-builds/issues/622

it is about any errors faced by users.
that day I was build the toolchain about 4-5 times using `--jobs=4` with diff options, and didn't faced with any error. so I have no ideas why users regularly faced with so strange errors...
I'm using VirtualBox on Linux with Win7-64bit, without any antivirus.

**Comment by zetab007** [comment]
You mean this one? [https://github.com/niXman/mingw-builds/issues/614](https://github.com/niXman/mingw-builds/issues/614)
My build option is quite different with that in this issue. In my experience, changing only one option will end-up with different error. Sometimes even with the same build option can end-up with different error. It's quite random, so I can't conclude anything.
I'm using native Win10 pro 64bit, with comodo firewall, no antivirus. I've check the log of firewall, no related activity.

**Comment by niXman** [comment]
and that too.
that issue is also very strange...
I can't imagine the `make` could do the things described by the author... otherwise any build of any software using `make` would end up with similar problems. but this is not.

**Comment by starg2** [comment]
Sounds like a concurrency issue to me. I vaguely recall binutils (especially dlltool) had concurrency bugs on Windows.

FYI, I usually set `--jobs=16` or even launch two instances with `--jobs=8` on my machine, but explicitly pass `-j1` to `make` when building `mingw-w64-crt`. Never encountered an issue like that.

> Another thing, I tried the `--provided-toolchain=<path>` option, using MSYS2's mingw32 toolchain for the building, and the building time became ridiculously long. 

Maybe this is related? [mingw packages now built with `-D_FORTIFY_SOURCE=2` and `-fstack-protector-strong`](https://www.msys2.org/news/)

**Comment by niXman** [comment]
> Sounds like a concurrency issue to me.

in `make`?
I can't imagine that.

> I vaguely recall binutils (especially dlltool) had concurrency bugs on Windows.

I didn't know that.
could you provide me a link to any bug report?

> but explicitly pass -j1 to make when building mingw-w64-crt. Never encountered an issue like that.

as you can see there is used `-j$JOBS` in the `mingw-w64-crt` build script and I never ran into any problems: https://github.com/niXman/mingw-builds/blob/develop/scripts/mingw-w64-crt.sh#L97

besides, for 11 years I have been building MinGW-W64 using only Win7. maybe that's why I didn't run into those problems...

**Comment by zetab007** [comment]
I tried to build with `--jobs=4` again, and still got the libgomp_f.h error, but this time on the different line:
```
libtool: compile:  /c/buildroot/i686-1220-win32-sjlj-rt_v10-rev0/build/gcc-12.2.0/./gcc/xgcc -B/c/buildroot/i686-1220-win32-sjlj-rt_v10-rev0/build/gcc-12.2.0/./gcc/ -L/mingw32/i686-w64-mingw32/lib -L/mingw32/mingw/lib -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/mingw/include -B/mingw32/i686-w64-mingw32/bin/ -B/mingw32/i686-w64-mingw32/lib/ -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/i686-w64-mingw32/sys-include -fno-checking -DHAVE_CONFIG_H -I. -I../../../../../src/gcc-12.2.0/libgomp -I../../../../../src/gcc-12.2.0/libgomp/config/mingw32 -I../../../../../src/gcc-12.2.0/libgomp/config/posix -I../../../../../src/gcc-12.2.0/libgomp -I../../../../../src/gcc-12.2.0/libgomp/../include -pthread -Wall -g -O2 -pipe -fno-ident -I/c/buildroot/i686-1220-win32-sjlj-rt_v10-rev0/mingw32/opt/include -I/c/buildroot/prerequisites/i686-zlib-static/include -I/c/buildroot/prerequisites/i686-w64-mingw32-static/include -MT error.lo -MD -MP -MF .deps/error.Tpo -c ../../../../../src/gcc-12.2.0/libgomp/error.c  -DDLL_EXPORT -DPIC -o .libs/error.o
In file included from C:/buildroot/src/gcc-12.2.0/libgomp/env.c:34:
./libgomp_f.h:44:7: error: operator '==' has no left operand
   44 | #if ( == ) \
      |       ^~
./libgomp_f.h: In function 'omp_check_defines':
./libgomp_f.h:79:18: error: expected expression before '!=' token
   79 |              ||  != sizeof (omp_nest_lock_t)
      |                  ^~
./libgomp_f.h:77:8: warning: unused variable 'test' [-Wunused-variable]
   77 |   char test[(4 != sizeof (omp_lock_t)
      |        ^~~~
```
These are options I used:
```
./build --mode=gcc-12.2.0 --buildroot=/c/buildroot --jobs=1 --rev=0 --rt-version=v10 --threads=win32 --exceptions=sjlj --arch=i686 --bin-compress --enable-languages=c,c++ --no-multilib --with-default-msvcrt=msvcrt --with-default-win32-winnt=0x0601
./build --mode=gcc-12.2.0 --buildroot=/c/buildroot --jobs=4 --rev=0 --rt-version=v10 --threads=win32 --exceptions=sjlj --arch=i686 --bin-compress --enable-languages=c,c++ --no-multilib --with-default-msvcrt=msvcrt --with-default-win32-winnt=0x0601
```
The only difference is the `--jobs` option. It passed the building with `--jobs=1`, but failed with  `--jobs=4`.

I noticed the build-in Windows Defender had obvious CPU activity during the building time.
I'll try turn off the Windows Defender, see if it's related.

**Comment by starg2** [comment]
> > I vaguely recall binutils (especially dlltool) had concurrency bugs on Windows.
> 
> I didn't know that. could you provide me a link to any bug report?

I just found this: [dlltool broke in 2.38](https://sourceware.org/bugzilla/show_bug.cgi?id=28885)

So that issue is specific to binutils 2.38. Since the default toolchains downloaded from sourceforge contain binutils 2.30, this issue only happens when `--provided-toolchain=` points to binutils 2.38.

I'll write a PR to update binutils to 2.39.

**Comment by starg2** [comment]
@zetab007 can you compare `libgomp_f.h` built with `--jobs=1` vs `--jobs=4`?

**Comment by niXman** [comment]
@zetab007 
> I tried to build with --jobs=4 again, and still got the libgomp_f.h error, but this time on the different line:

will try now with 4 jobs.

> I just found this: [dlltool broke in 2.38](https://sourceware.org/bugzilla/show_bug.cgi?id=28885)

oh, really...

> I'll write a PR to update binutils to 2.39.

it would be great!
could you please update the links to the downloadable host toolchains too?

**Comment by starg2** [comment]
> could you please update the links to the downloadable host toolchains too?

Do you mean the build script should be updated to download toolchains from GitHub releases?

**Comment by niXman** [comment]
yes please

**Comment by niXman** [comment]
@zetab007 

done, the `mingw-w64-crt` building was successful.

**Comment by niXman** [comment]
github reordered my comments for some reason %)

**Comment by starg2** [comment]
> github reordered my comments for some reason %)

Same here. And some of the comments were posted in the future!

**Comment by starg2** [comment]
> yes please

@niXman I got it.  Could you publish a new release with binutils 2.39 first? The current release contains the buggy binutils 2.38.

**Comment by niXman** [comment]
ah, right!

then it will be 12.2.0-rev1 ?

**Comment by starg2** [comment]
> then it will be 12.2.0-rev1 ?

Yes.

**Comment by zetab007** [comment]
Building with --jobs=4 was done without error. Looks like those errors were caused by Windows Defender.

**Comment by starg2** [comment]
Nice. Has the `GetSystemTimePreciseAsFileTime` problem been resolved as well?

**Comment by niXman** [comment]
ah, really %)
the required flags are in another branch: https://github.com/niXman/mingw-builds/commit/15add2aa0f91a9c46720cfd50ccd31f01866c8eb

**Comment by zetab007** [comment]
> Nice. Has the `GetSystemTimePreciseAsFileTime` problem been resolved as well?

Yes, adding `--with-default-win32-winnt` option solve that problem.

**Comment by zetab007** [comment]
I just noticed the win32-sjlj variant was removed in latest release, can I still build this variant in the future?

**Comment by niXman** [comment]
yes, look at this: https://github.com/niXman/mingw-builds/pull/628

**Comment by niXman** [comment]
@zetab007 is the issue solved?

**Comment by zetab007** [comment]
> @zetab007 is the issue solved?

Yes.

**Comment by niXman** [comment]
then could you close it please? =)

**Comment by nikic** [comment]
I was wondering whether there is any interest in using `--with-default-win32-winnt=0x0601` for the pre-built toolchains on this repo?

**Comment by niXman** [comment]
could you read this issue?

**Comment by nikic** [comment]
> could you read this issue?

Not sure what you're trying to say here. The `--with-default-win32-winnt` option was added to allow fixing this issue by performing a custom build. At some of the intermediate comments it sounded like you wanted to support Windows 7 by default (with https://github.com/niXman/mingw-builds/commit/aec18ddacb2a9696b50364e77270b609c30abce3 landing on `develop` for example), but as far as I understood, in the end Windows 7 ended up being not supported by the builds produced in this repo. I'm just trying to confirm whether that's the intended end result or not.

**Comment by niXman** [comment]
> The --with-default-win32-winnt option was added to allow fixing this issue

right.

> but as far as I understood, in the end Windows 7 ended up being not supported by the builds produced in this repo.

how did you come to that conclusion?

**Comment by niXman** [comment]
`0x0601` for `_WIN32_WINNT` means Win7
