### ISSUE TITLE
Provide UCRT toolchains

### ISSUE THREAD

**Issue by starg2** [niXman/mingw-builds-binaries#29]
MSYS2 has recently changed the default environment from msvcrt-based MINGW64 to ucrt-based UCRT64: https://www.msys2.org/news/

Maybe it's time for mingw-builds to release ucrt-based binaries?

**Comment by niXman** [comment]
> Maybe it's time for mingw-builds to release ucrt-based binaries?

yes, that was the plan. instead of SJLJ builds.

**Comment by niXman** [comment]
@starg2 I think we should do some renaming for the archives because of that.
should we add `ucrt` for ucrt built archives, and `msvcrt` for the second?
for example:
`x86_64-12.2.0-release-posix-seh-msvcrt-rt_v10-rev1.7z` or `x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev1.7z` ?

**Comment by starg2** [comment]
Yes, that makes sense.

**Comment by starg2** [comment]
Once a new release is published, the build script should be updated to download UCRT toolchains when `--with-default-msvcrt=ucrt` is specified.

Also, msvcrt/ucrt option should be added to the online installer.

**Comment by niXman** [comment]
> Once a new release is published, the build script should be updated to download UCRT toolchains when --with-default-msvcrt=ucrt is specified.

ah, right.

> Also, msvcrt/ucrt option should be added to the online installer, preferably defaulting to ucrt.

sure, will ask the developer.

**Comment by niXman** [comment]
@starg2 I understand correctly that ucrt is only available for 64bit builds?

**Comment by starg2** [comment]
> @starg2 I understand correctly that ucrt is only available for 64bit builds?

I don't think so. I've been successfully building 32-bit ucrt toolchains for some time.

MSYS2 doesn't have ucrt32 simply because there is little demand for it.

**Comment by niXman** [comment]
ah, got it. thanks!

**Comment by niXman** [comment]
so, I have successfully built the following builds locally: gcc-12.2.0, i686/x86_64, seh/dwarf, win32/posix.

so, the final list of builds looks like this:
1) `x86_64-12.2.0-posix-seh-msvcrt-rt_v10`
2) `x86_64-12.2.0-win32-seh-msvcrt-rt_v10`
3) `x86_64-12.2.0-posix-seh-ucrt-rt_v10`
4) `x86_64-12.2.0-win32-seh-ucrt-rt_v10`
5) `i686-12.2.0-posix-dwarf-msvcrt-rt_v10`
6) `i686-12.2.0-win32-dwarf-msvcrt-rt_v10`

@starg2 right?

**Comment by niXman** [comment]
is there any reason to build i686+ucrt too?

**Comment by starg2** [comment]
Sorry. I've been busy these days.

> is there any reason to build i686+ucrt too?

I think i686+ucrt is nice to have because that configuration is not provided by MSYS2.

----

Or you can drop i686 entirely because it's 2022.

**Comment by niXman** [comment]
according to the firefox hardware report (https://data.firefox.com/dashboard/hardware), there is ~16% of users who use 32-bit Windows...

**Comment by starg2** [comment]
I see. Let's keep i686 then.

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds-binaries/releases/tag/12.2.0-rt_v10-rev2

**Comment by niXman** [comment]
as the last atep we need to change the build scripts so that they use UCRT builds as host toolchain for UCRT builds. and MSVC for MSVC builds.

**Comment by niXman** [comment]
will close this issue after that.
