### ISSUE TITLE
Fortran language is missing from enabled-languages

### ISSUE THREAD

**Issue by cristianadam** [niXman/mingw-builds-binaries#3]
MinGW 8.1.0 release (and previous) on https://sourceforge.net/projects/mingw-w64/files/ has had `fortran` as part of the `enabled-languages` build script.

As it turns out fortran was used and users are missing it from the MinGW package that I've built, as reported at https://forum.qt.io/topic/133616/qt-6-2-2-and-mingw-9-0-0-does-not-deliver-a-fortran-compiler/ 

Adding `fortran` doesn't break things as seen at https://github.com/cristianadam/mingw-builds/actions/runs/1709598486 and it makes the 7zip archive 5MB bigger and the installed size 44MB bigger.

**Comment by niXman** [comment]
@cristianadam in process: https://github.com/niXman/mingw-builds-binaries/actions/runs/1722891166
