### ISSUE TITLE
win32 threads

### ISSUE THREAD

**Issue by nenin-sc** [niXman/mingw-builds-binaries#32]
Hi,
there is a patch for win32 threads from  Jamaika1  https://github.com/Jamaika1/mingw_std_threads
Is it possible/reasonable to apply it for builds? 
I tried it, in simple cases it looks like working. 
Thanks for your job and Happy NY!

**Comment by niXman** [comment]
hi,

no need to use some 3rdparty patches for this because the support for WIN32 threads already tested and applied for gcc `master` and will be enabled in builds starting at gcc-13 ;)

Happy NY too!


ps
please close if you have no other questions.

**Comment by nenin-sc** [comment]
Thanks for intriguing news!
