### ISSUE TITLE
No gdb tui?

### ISSUE THREAD

**Issue by quadro9** [niXman/mingw-builds-binaries#33]
(gdb) layout
Undefined command: "layout".  Try "help".
(gdb)

**Comment by niXman** [comment]
yea, TUI was disabled for some reason: https://github.com/niXman/mingw-builds/blob/develop/scripts/gdb.sh#L80

**Comment by niXman** [comment]
@quadro9 could you please create an issue on mingw-builds project?

**Comment by quadro9** [comment]
need I close issue here?

**Comment by niXman** [comment]
sure, thanks!
