### ISSUE TITLE
gcc gives error if you try to use it without being in the PATH environment variable

### ISSUE THREAD

**Issue by rockcavera** [niXman/mingw-builds-binaries#34]
I usually have a few compilers and I don't leave them all in the PATH. So just access by typing the whole path to it. In this, I ended up discovering that the binary i686 and x86_64, gcc version 12.2.0, rev2, when called that way, that is, without being in the PATH, present the following error of missing libwinpthread-1.dll. The problem can be easily resolved by copying libwinpthread-1.dll to "mingw64\libexec\gcc\x86_64-w64-mingw32\12.2.0". After that, I checked all the executables there and they all have a dependency on this dll.

I also verified that the executables in "mingw64\x86_64-w64-mingw32\bin" depend on libwinpthread-1.dll and libstdc++-6.dll (if I'm not mistaken it's just ld.gold.exe).

In my opinion, there are 3 ways to solve this:
1) the user himself makes the copy, when he witnesses the error and understands how to mitigate it;
2) the binaries are released with the copies already made; or
3) the binaries are compiled statically.

![mingw64-fora-do-path](https://user-images.githubusercontent.com/21215323/212703771-d9a0575d-47d9-45a7-b80d-2545008982ff.png)

**Comment by niXman** [comment]
yeah, it is known issue.

it will be partially fixed starting from GCC-13. in that version it will be possible to create symlinks to the executables and it will be resolved correctly.

but for the most part I agree, will think about this...


thank you!

**Comment by niXman** [comment]
but wait.
using my working build of GCC-12.2.0 it works as it should...

**Comment by nenin-sc** [comment]
Hi,
there is relatively simple way to use multiple versions of compiler:
1. Add to PATH record like this '%MINGW64_PATH%\bin'
2. Create *.bat file for each installation like this
`setx MINGW64_PATH  c:\mingw64\nixman12_2w32u`
3. Use appropriate  *.bat file to switch to desired version of the compiler.  
At least at Pro version of the windows it works.

**Comment by rockcavera** [comment]
> but wait. using my working build of GCC-12.2.0 it works successfully in the same situation... %)

Maybe opening a cmd and typing `set path=""` can test if somewhere has the dll and is making it work normally.


> Hi, there is relatively simple way to use multiple versions of compiler:
> 
> 1. Add to PATH record like this '%MINGW64_PATH%\bin'
> 2. Create *.bat file for each installation like this
>    `setx MINGW64_PATH  c:\mingw64\nixman12_2w32u`
> 3. Use appropriate  *.bat file to switch to desired version of the compiler.
>    At least at Pro version of  MS Windows 7 & 10 it works.

I use a batch script to select the Nim compiler version. It's a viable way, but it wouldn't solve the real problem, which would be the executable always having the dlls it depends on "nearby" without assuming that these dlls are in the PATH.

**Comment by niXman** [comment]
> Maybe opening a cmd and typing set path="" can test if somewhere has the dll and is making it work normally.

I understood the reason why it is works for me: because the toolchain I'm used for that test, was built using the patch for symlinks resolution =)

**Comment by niXman** [comment]
closed.
