### ISSUE TITLE
Fail while read array of char using cin

### ISSUE THREAD

**Issue by zhuangbo** [niXman/mingw-builds-binaries#35]
The following program will fail under g++ 12.

g++ version 12.2.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project)

OS: Windows 11

```c++
#include <iostream>
using namespace std;

int main()
{
    char s[256];
    cin >> s;
    cout << s;
    return 0;
}
```

Compile and run
```bash
g++ test.cpp
./a
```
Then the program fail at `cin >> s`, and output nothing.

**Comment by fskoras** [comment]
it's a C++ program, so you need to compile it with g++, not gcc

**Comment by zhuangbo** [comment]
> it's a C++ program, so you need to compile it with g++, not gcc

Thank you.
Yes, I use g++ to compile it.
g++ 12.2.0, Windows 11

**Comment by niXman** [comment]
and? what is your question?

**Comment by zhuangbo** [comment]
> and? what is your question?

Why `cin >> s`  will fail in the program?
I use g++ 12.2.0 on Windows 11.

**Comment by niXman** [comment]
why don't you want to show the error message?

**Comment by zhuangbo** [comment]
> why don't you want to show the error message?

Thank you.
The program crashed without any message.

First, show the g++ version.
```
d:\Documents\cpp\tests> g++ -v
Using built-in specs.
COLLECT_GCC=g++
......
gcc version 12.2.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project)
```
Then, compile the program above `test.cpp`.
```
d:\Documents\cpp\tests>g++ -g test.cpp
```
Finally, I try to run it in gdb but crashed.
```
d:\Documents\cpp\tests>gdb a.exe
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.exe...
(gdb) l
warning: Source file is more recent than executable.
1       #include <iostream>
2       using namespace std;
3
4       int main()
5       {
6           char s[256];
7           cin >> s;
8           cout << s;
9           return 0;
10      }
(gdb) r
Starting program: d:\Documents\cpp\tests\a.exe
[New Thread 15448.0x7348]
[New Thread 15448.0x63c8]
[Thread 15448.0x3a4c exited with code 3221225785]
[Thread 15448.0x7348 exited with code 3221225785]
During startup program exited with code 0xc0000139.
(gdb)
```

**Comment by zhuangbo** [comment]
OK. Compile and run the following code.
```cpp
#include <cstdio>
int main()
{
   std::printf("hello!");
}
```
It prints `hello!`. That's right.

I found `printf` and `scanf` are all OK, but `cin >> s` (`char s[]` here) will crash. 
```cpp
#include <iostream>
using namespace std;

int main()
{
    char s[256];
    // cin >> s;    // will crash here, why?
    scanf("%s", s); // OK
    cout << s;
    return 0;
}
```
This makes me confused, and I don't know where the problem is.

**Comment by niXman** [comment]
try to replace `s` with `std::string`.

**Comment by zhuangbo** [comment]
`std::string` is also OK, but `char s[]` will crash.

**Comment by niXman** [comment]
OK, please show me the output for `g++ -v`, and the cmd you are using for compile the c++ example.

BTW, I never used used `cin` with char array before =)

**Comment by nenin-sc** [comment]
Hi all,
just tested with last ucrt build. Looks like there are no problem, behavior is as it expected.
Dear **zhuangbo**, please note  that you can entry no more than 255 chars in  "char s[256]". And I dont know what happens if you will try to enter something _unicodish_.

**Comment by zhuangbo** [comment]
Thank you.

I use [x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev2.7z](https://www.virustotal.com/gui/file/dc1f299e8450c96f59f4b8f7c1290ebb78ee00ddb71f9ed4ca0efaf5462f8c4e)

Show the g++ version.
```
PS D:\Documents\cpp\tests> g++ -v
Using built-in specs.
COLLECT_GCC=C:\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-12.2.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64 --enable-host-shared --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev2, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64/opt/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-zlib-static/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64/opt/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-zlib-static/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64/opt/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-zlib-static/include -I/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64/opt/lib -L/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-zlib-static/lib -L/c/mingw-builds/ucrt64-seh-posix/prerequisites/x86_64-w64-mingw32-static/lib ' LD_FOR_TARGET=/c/mingw-builds/ucrt64-seh-posix/x86_64-1220-posix-seh-ucrt-rt_v10-rev2/mingw64/bin/ld.exe --with-boot-ldflags=' -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 
```
Test code:
```cpp
#include <iostream>
using namespace std;

int main()
{
    char s[256];
    cin >> s;      // will crash here before input anything
    cout << s;
    return 0;
}
```
Compile and run:
```
PS D:\Documents\cpp\tests> g++ .\test.cpp
PS D:\Documents\cpp\tests> .\a.exe
```
**The program crashed before I can input anything.** 
This makes me confused, and I don't know where the problem is.

Then, I try to debug it. But I cannot run the program, it says
**During startup program exited with code 0xc0000139.**
```
PS D:\Documents\cpp\tests> g++ -g .\test.cpp
PS D:\Documents\cpp\tests> gdb .\a.exe
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from .\a.exe...
(gdb) l
1       #include <iostream>
2       using namespace std;
3
4       int main()
5       {
6           char s[256];
7           cin >> s;
8           cout << s;
9           return 0;
10      }
(gdb) r
Starting program: D:\Documents\cpp\tests\a.exe
[New Thread 9576.0xfb4]
[New Thread 9576.0xfb8]
[Thread 9576.0x27b4 exited with code 3221225785]
[Thread 9576.0xfb8 exited with code 3221225785]
During startup program exited with code 0xc0000139.
(gdb) q
PS D:\Documents\cpp\tests> 
```

**Comment by nenin-sc** [comment]
May it be a PowerShell console issue?

**Comment by niXman** [comment]
no ideas, sorry. I never used it.

**Comment by nenin-sc** [comment]
Dear **zhuangbo**, you can try to run your app in cmd.

**Comment by zhuangbo** [comment]
@niXman Thanks,  but the code should works in C++, and I know it works well in early version, e.g. [MinGW-W64 GCC-8.1.0](https://sourceforge.net/projects/mingw-w64/files/).

@nenin-sc Thanks.
But it does not work in Power Shell or CMD. The input statement `cin >> s` never be executed.

In Power Shell:
![image](https://user-images.githubusercontent.com/1687351/217708670-b6ec512a-a8c7-42f4-8379-7ba6079a2216.png)

In CMD:
![image](https://user-images.githubusercontent.com/1687351/217709001-e82e2b7d-26df-4107-a32b-f6ac5b992f04.png)

**Comment by nenin-sc** [comment]
Hi again,
I asked colleague to run statically-linked app on Win11, looks like it works.
Other thing I can suspect that it might be corrupted ucrt installation (kind of _dll hell_ issue).

**Comment by niXman** [comment]
will check too, on win7. I dont have other windows atm.

**Comment by niXman** [comment]
it works as it should:
![image](https://user-images.githubusercontent.com/518474/217757415-df8537e0-f796-42d4-969e-d3dab3f64a71.png)

@zhuangbo I have no ideas what the problem you are faced but this issue is not specific to the compiler.

**Comment by starg2** [comment]
`0xc0000139 == STATUS_ENTRYPOINT_NOT_FOUND`, so this definitely looks like a DLL hell.

**Comment by niXman** [comment]
fck %)

**Comment by zhuangbo** [comment]
Oh!
Is this problem because a DLL library file is missing from my computer?
Is there any way to determine which DLL is missing?
@starg2

**Comment by niXman** [comment]
@zhuangbo I'm more interested in why you said that when using `std::string` the program works correctly.
this cannot be. it doesn't depend on using `std::string` or NOT using `std::string`...

> Is there any way to determine which DLL is missing?

https://dependencywalker.com/

**Comment by zhuangbo** [comment]
OK, thank you.
In my computer (Win 11, 22H2, 22621.1194), the following program using `std::string` works correctly.
```cpp
#include <iostream>
using namespace std;

int main()
{
    string s;  // string s is OK, but char s[256]; not work
    cin >> s;
    cout << s;
    return 0;
}
```
However, it will not work if repace `string s;` to `char s[256];`.

> BTW: Denpendency walker give the following result.
> - Program using `char s[]`
> > ![image](https://user-images.githubusercontent.com/1687351/217851151-898ac0f4-1514-499d-9529-86417482c88a.png)
>
> - Program using `std::string`
> > ![image](https://user-images.githubusercontent.com/1687351/217853253-fd656fb1-9dd3-43b5-bc9c-b49a9220ae61.png)

**Comment by nenin-sc** [comment]
I checked both packeges,
x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev2.7z
x86_64-12.2.0-release-win32-seh-ucrt-rt_v10-rev2.7z
function **_ZSt17_istream_extract_RSiPcx**   is available in libstdc++-6.dll 
Dear **zhuangbo**, do you have other distribution of the Mingw or installed software, which is built using Mingw?
Did you tried static linking?

**Comment by zhuangbo** [comment]
Yes, I tested the same program `test.cpp` with different distribution of mingw.
Compile using
(1) static linking: `g++ -static-libstdc++ .\test.cpp`
(2) dynamic linking command: `g++ .\test.cpp`
And then run it: `.\a.exe`

- x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev2.7z
  - the _static linking_ is **OK** 
  - dynamic linking **not work**.  This is the strange problem I have encountered.
- x86_64-8.5.0-release-posix-seh-rt_v10-rev0.7z
  - the _static linking_ is **OK**
  - dynamic linking is **OK**
- x86_64-posix-seh (MinGW-W64 GCC-8.1.0) https://sourceforge.net/projects/mingw-w64/files/
  - the _static linking_ is **OK**
  - dynamic linking is **OK**

> BTW: The test program `test.cpp` is as follows.
> ```cpp
> #include <iostream>
> using namespace std;
> 
> int main()
> {
>     char s[256];
>     cin >> s;
>     cout << s;
>     return 0;
> }
> ```

**Comment by nenin-sc** [comment]
So, it is _dll hell_ as it is. Your dynamically-linked program finds somehow wrong dll from different gcc version, which is not compatible with gcc 12.20 ucrt .

**Comment by zhuangbo** [comment]
OK, thank you very much. @nenin-sc
