### ISSUE TITLE
【BUGBUGBUG!!!!!】bin\string.exe param error~~~pls fix it 

### ISSUE THREAD

**Issue by nop4LOL** [niXman/mingw-builds-binaries#36]
strings.exe -h

--unicode={default|show|invalid|hex|escape|highlight}
  -U {d|s|i|x|e|h}          Specify how to treat UTF-8 encoded unicode characters

option  {s} - show  is  error  ,can't use , d|i|x|e|h is ok, only s cant work and warning:

strings.exe: invalid argument to -U/--unicode: s

**Comment by niXman** [comment]
have you tried to change the codepage to 65001?
https://stackoverflow.com/a/27622364

**Comment by nop4LOL** [comment]
> have you tried to change the codepage to 65001? https://stackoverflow.com/a/27622364

hi sir，it impossible 65001 problem, or -U s | e | and more param will all show error.

but I also try to chcp 65001 to try again , this is the result , the same as before ,so this is a bug, please fix it ~~~ 

 's' can't use , others ok !

![image](https://user-images.githubusercontent.com/117899311/226566420-79fd7ae9-7b1d-4849-9f71-2ed2f89c2613.png)

**Comment by nop4LOL** [comment]
maybe in source code , you type error 's' to other char ?? please review it .

**Comment by starg2** [comment]
`-U s` is not listed in [the official documentation](https://sourceware.org/binutils/docs/binutils/strings.html) and [not implemented at all](https://github.com/bminor/binutils-gdb/blob/binutils-2_39/binutils/strings.c#L278).

It's probably a typo in the help message.

**Comment by niXman** [comment]
thank you @starg2 for the note!

@nop4LOL please close.

**Comment by nop4LOL** [comment]
> `-U s` is not listed in [the official documentation](https://sourceware.org/binutils/docs/binutils/strings.html) and [not implemented at all](https://github.com/bminor/binutils-gdb/blob/binutils-2_39/binutils/strings.c#L278).
> 
> It's probably a typo in the help message.

you mean I am wrong ,sir ?? see the latest version from mingw\bin\strings.exe @niXman 

![image](https://user-images.githubusercontent.com/117899311/227789116-db9c662c-c8f0-43d3-86a9-367027d57743.png)

**Comment by niXman** [comment]
@nop4LOL please close or try to implement the functionality.
