### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by Kibouo** [niXman/mingw-builds-binaries#37]
Hello there,

This build is provided via Chocolatey on Windows (https://community.chocolatey.org/packages/mingw) where I installed the latest version (12.2.0.03042023). I am trying to run gdb with gef (python extensions). However, on load I get the error `ModuleNotFoundError: No module named '_ctypes'`.

Googling the error gave basically 2 results:
- people on Linux saying that installing `libffi` fixes the error. I am on Windows however.
- issue https://github.com/msys2/MINGW-packages/issues/4572 that implemented a patch `1900-ctypes-dont-depend-on-internal-libffi.patch`. I do not know if this is applicable here.

Env info:
```
Edition	Windows 11 Pro N
Version	22H2
Installed on	‎7/‎05/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
```

```
 ; gcc --version
gcc.exe (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The bundled python is
```
# pwd = C:\programdata\chocolatey\lib\mingw\tools\install\mingw64\opt\bin
 ; .\python3.9.exe
Python 3.9.10 (heads/mingw-v3.9.10-dirty:12d1cb5b7c, Dec  9 2022, 03:24:49)  [GCC UCRT 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import _ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_ctypes'
```

![image](https://user-images.githubusercontent.com/25766329/227033947-cef2415e-a6c8-4282-be2d-37a3c55f4d5c.png)

**Comment by Kibouo** [comment]
Is this possibly related to a mismatch between gef's required Python version, and the Python version provided by this package?

**Comment by niXman** [comment]
great, then just try to build the toolchain using the patch you mentioned above, and let us know.

you need to put the patch into `mingw-builds/tree/develop/patches/Python3` directory and add the file path here: https://github.com/niXman/mingw-builds/blob/develop/scripts/python-3.sh#L57

**Comment by niXman** [comment]
@Kibouo any progress?
