### ISSUE TITLE
13.1.0-rt_v11-rev0 has no binaries

### ISSUE THREAD

**Issue by cristianadam** [niXman/mingw-builds-binaries#39]
At https://github.com/niXman/mingw-builds-binaries/releases/tag/13.1.0-rt_v11-rev0 there are no binaries listed.

This is due to https://github.com/niXman/mingw-builds-binaries/actions/runs/5036456410/jobs/9032617873 which fails with:

```
(1/1) Updating the info directory file...
bad command line: " --mode=gcc-13.1.0". terminate.
done
```

I guess https://github.com/niXman/mingw-builds-binaries/commit/9eef2aec7f60821591de540e7304434d70897739 broke dues to newlines.

**Comment by tomay3000** [comment]
Same problem as of **Release of 13.1.0-rt_v11-rev1**

**Comment by Fsu0413** [comment]
It seems rev1 is running timeout on x86_64 ucrt builds.

**Comment by starg2** [comment]
13.1.0-rt_v11-rev1 is now available.
