### ISSUE TITLE
Gen:Variant.Ransom.Hive.9 antivirus report

### ISSUE THREAD

**Issue by xana43** [niXman/mingw-builds-binaries#41]
For some reason when I try to download the latest mingw binary it triggers my antivirus saying "Gen:Variant.Ransom.Hive.9", this is with version "13.1.0-rt_v11-rev1". However the previous version "12.2.0-rt_v10-rev2" doesn't cause this. I am unsure if this is a false positive or if it's actually an issue.

**Comment by starg2** [comment]
13.1.0-rt_v11-rev1 was built on GitHub Actions using 12.2.0-rt_v10-rev2 as a host toolchain.

Unless GitHub Actions or any of the source archives is compromised (which is unlikely), it should be safe.

**Comment by xana43** [comment]
Upon further investigation it seems that the particular file that my antivirus is complaining about is 'gcov.exe' that might explain it considering what some things in MinGW does. hopefully this can eventually get officially resolved. for now I'm going to exempt the archive from the antivirus scanning

**Comment by nenin-sc** [comment]
I downloaded it and made brief tests, no AV problem observed under Eset Endpoint.
