### ISSUE TITLE
Segmentation Fault "x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1"

### ISSUE THREAD

**Issue by urbans0ft** [niXman/mingw-builds-binaries#43]
**Building and executing a simple "Hello World!" with the newest release yields a segmentation fault:**

# x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1

```cpp
#include <iostream>
using namespace std;
int main(int argc, char* argv[])
{
    cout << "Hello World!" << endl;
    return 0;
}
```

Build:
```
g++.exe -fdiagnostics-color=always -g main.cpp -o main.exe
```

vscode:
![image](https://github.com/niXman/mingw-builds-binaries/assets/20521499/ab53f892-15e8-4f1a-bab3-570c3d714efe)

# x86_64-12.2.0-release-win32-seh-ucrt-rt_v10-rev2

Building, debugging, executing with the prior release works like a charm.

# System

Tested on a windows sandbox system:

```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 2 GenuineIntel ~2712 Mhz
BIOS Version:              Microsoft Corporation Hyper-V UEFI Release v4.0, 11/1/2019
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
Total Physical Memory:     4,095 MB
Available Physical Memory: 1,819 MB
Virtual Memory: Max Size:  5,823 MB
Virtual Memory: Available: 3,209 MB
Virtual Memory: In Use:    2,614 MB
Page File Location(s):     C:\pagefile.sys
```

**Comment by urbans0ft** [comment]
@nenin-sc BTW: Using the [w64devkit](https://github.com/skeeto/w64devkit) works:

```
C:\nenin-sc>g++ main.cpp

C:\nenin-sc>a.exe
increase global counter with 10 threads...
increase counter (foo) with 10 threads using reference...
increase counter (bar) with 10 threads using member...
synchronizing all threads...
global_counter: 10000
foo: 10000
bar: 10000

C:\nenin-sc>g++ --version
g++ (GCC) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

From my point of view there's definitely something wrong with [this](https://github.com/niXman/mingw-builds-binaries/releases/tag/13.1.0-rt_v11-rev1) release. At least with the asset x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1.7z .

**Comment by nenin-sc** [comment]
I can only suppose that you have kind of dll hell. By some reasons niXman release  catch dll from different distribution. Did you try static linking?

**Comment by starg2** [comment]
`-1073741819` == `0xC0000005` == `STATUS_ACCESS_VIOLATION`

> I can only suppose that you have kind of dll hell.

I second that.

@urbans0ft Try running `where libstdc++-6.dll` and see if the right dll is listed first.

**Comment by niXman** [comment]
any news with this? or may I close?

**Comment by urbans0ft** [comment]
@niXman Sorry had no time to retry (will close, see below).
@starg2 Damn, you were right.

```
>where libstdc++-6.dll
C:\Run\libstdc++-6.dll
C:\mingw64\bin\libstdc++-6.dll
```

Changing the order solved the problem. Thank you very much.
