### ISSUE TITLE
Linking fails if installed in a shared folder

### ISSUE THREAD

**Issue by bswebdk** [niXman/mingw-builds-binaries#46]
I do not know whether this is a (known) bug or not, but I've spend quite some time with this issue before I figured it out and I think this should either be fixed or noted as a known issue, I could not find any info about it anywhere.

I have Windows installed in a VM using VirtualBox and I have a shared folder between host and client OS. I have placed MinGW-w64  in the root folder of the share which is mounted to Z: in Windows. I have added "Z:\mingw32\bin" to the PATH environment variable and compiling works as expected, but linking fails with:

`//VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find //VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/lib/../lib/crt2.o: Invalid argument
//VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find //VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/crtbegin.o: Invalid argument
//VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find //VBoxSvr/Share/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.1.0/crtend.o: Invalid argument
collect2.exe: error: ld returned 1 exit status`

Regardless of what I do, I cannot get it to work - most likely because of the "//" in the path. Copying MinGW-w64 to C:\mingw32 and adjusting the PATH variable accordingly makes the issue disappear.

**Comment by niXman** [comment]
> most likely because of the "//" in the path

I have no ideas how MInGW-W64-builds can handle the trouble you are talking about...

**Comment by niXman** [comment]
closed.
