### ISSUE TITLE
Are these builds official releases?

### ISSUE THREAD

**Issue by alvinhochun** [niXman/mingw-builds-binaries#5]
Hi, are these builds are considered "official releases", in the same vein as the older builds at https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/? I ask because I don't see this repository or any of these releases being linked from https://github.com/niXman/mingw-builds.

**Comment by niXman** [comment]
hi,

yes.
