### ISSUE TITLE
gcov.exe must be malware

### ISSUE THREAD

**Issue by kajihara-kiyohiko** [niXman/mingw-builds-binaries#51]
I installed x86_64-13.1.0-release-win32-seh-msvcrt-rt_v11-rev1.7z in https://github.com/niXman/mingw-builds-binaries/releases,  my anti-malware software notifies me that gcov.exe is malware. Also VirusTotal indicates that it is malware (see https://www.virustotal.com/gui/file/0dce658138023ab7aefb4d0ddd82aac8020fe4e7881db8a27cf0c4180bbfd618/detection).  I suggest you investigate.

**Comment by nenin-sc** [comment]
I checked my collections of mingws and can confirm, that gcov from gcc 13 generates false positives on VirusTotal.

**Comment by Peter0x44** [comment]
Getting flagged by Microsoft's protection racket scheme doesn't indicate something is malware
