### ISSUE TITLE
GCC 9.x or 10.x Win32 Thread

### ISSUE THREAD

**Issue by iceman50** [niXman/mingw-builds-binaries#52]
I was wondering if by some small chance you had a 9.x or 10.x that has win32 threading?

**Comment by nenin-sc** [comment]
You can try Jamaika patch  https://github.com/Jamaika1/mingw_std_threads/tree/main/m64-1X00/include/C%E2%81%BA%E2%81%BA
or https://github.com/meganz/mingw-std-threads for the older versions.

**Comment by iceman50** [comment]
I was actually asking for a specific build as I've seen others have successfully done in the past. I am not aware of MinGW-w64 builds with GCC 9.x or 10.x with Win32 threads available anywhere and that's why I was asking.

**Comment by nenin-sc** [comment]
> I've seen others have successfully done in the past

At my best knowledge and first hand experience all build before gcc 13 had stub for Win32 threads, without implementation.  While **meganz**  proposed solution many years ago, by some reasons developers of the GCC implemented it in last version only. As far as I understood, key issue was fact that threads are part not of MinGW64-w, but of  the standard C++ lib of GCC and GCC developers was not hurry to implement them, may be because of (c) issues. 
So for simple cases there are third-party patches, but there is no guarantee for 100% functionality required by standard. 
There is some discussion about: https://github.com/meganz/mingw-std-threads/issues/57

**Comment by starg2** [comment]
@iceman50, do you want gcc 9.x or 10.x with win32 threading as-is (without `std::thread` implementation) or with win32 native `std::thread` implementation backported?

As @nenin-sc mentioned, the win32 thread model gained support for `std::thread` only since gcc 13.

**Comment by nenin-sc** [comment]
> @iceman50, do you want gcc 9.x or 10.x with win32 threading as-is (without `std::thread` implementation) or with win32 native `std::thread` implementation backported?

Just in case: it might be interesting to have XP-compatible back-port. At least for me :)

**Comment by starg2** [comment]
> Just in case: it might be interesting to have XP-compatible back-port. At least for me :)

AFAIK, the win32 threading implementation in gcc 13 depends on `CONDITION_VARIABLE`, introduced in Windows Vista.

**Comment by nenin-sc** [comment]
> introduced in Windows Vista.

So I still stay on gcc 9 with meganz patch. :(

**Comment by iceman50** [comment]
I am looking for win32 threading as-is no backport, and with the MSVCRT not the UCRT.

**Comment by nenin-sc** [comment]
> win32 threading as-is

Lets make things clear: win32 threading is:
1. std::thread implemented on top of Win32 API threading functions
2. Win32 API threading functions

In first case there are two options:
1. Using patches I listed
2. Back-porting from GCC 13

In second case you always can use Win API form MinGW.

Concerning UCRT vs. MSVCRT: up to you, but  MSVCRT is some strange set of dlls, which originated from depth of the 90th (VC6) and it is not actual C runtime for last 20 years. It is used by MS by obscure reasons and might simply disappear after next safety patch. UCRT  can be installed down to WinXP and it is real C runtime, safe and optimized as good as it can be done in Windows.

**Comment by starg2** [comment]
> I am looking for win32 threading as-is no backport, and with the MSVCRT not the UCRT.

Got it. Fortunately, gcc 10.5.0 is still available here: https://github.com/starg2/mingw-builds/actions/runs/5485122896

**Comment by niXman** [comment]
@iceman50 please close the issue if you have no additional questions.
