### ISSUE TITLE
MCF thread model missing from release

### ISSUE THREAD

**Issue by simondeschenes** [niXman/mingw-builds-binaries#57]
I was interestrd in getting the MCF thread model build after seeing the Release notes.

- MCF thread model was added

However, there is no corresponding build to download. Win32 and posix thread models are the only options available for the binaries in this release (just like the previous releases):

https://github.com/niXman/mingw-builds-binaries/releases/tag/13.2.0-rt_v11-rev0

Where can I download the MCF build?

**Comment by niXman** [comment]
hi,

you are right, last time I ran the build before MCF was added to the build matrix.
will re-build again using `rev1` revision tag within a few days.

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds-binaries/releases/tag/13.2.0-rt_v11-rev1
