### ISSUE TITLE
suggest to decrease unnecessory files

### ISSUE THREAD

**Issue by anbangli** [niXman/mingw-builds-binaries#59]
One day,  I thecked the total amount of files in MinGW-w64 GCC release package v13.2,  and found that there are about 14,856 files.

I felt that there may be some unnecessory files. So I checked the amount of files in each directory,  and found there are a lot of files which seem to be unnecessory.

(1) There is a directory named "terminfo" in .\opt\lib\ whose total size is only 8.91M but contains 2,777 files and 42 directories.  Besides,  there is a dublicated copy of "terminfo" in .\opt\share\,  which also contains 2,777 files and 42 directories.

It is discribed in webpage "https://www.man7.org/linux/man-pages/man5/terminfo.5.html" as follows: 
Terminfo is a database describing terminals, used by screen-oriented programs such as nvi(1), lynx(1), mutt(1), and other curses applications, using high-level calls to libraries such as curses(3X). It is also used via low-level calls by non-curses applications which may be screen-oriented (such as @CLEAR@(1)) or non-screen (such as @TABS@(1)).

I also heard that "Terminfo" exists in /usr/share/terminfo in Linux. So, maybe Terminfo is important in Linux. However, is it necessory to keep two copied in GCC release? 

(2) The directory of .\opt\share\doc contains 3,994 files. Especially,  the sub-directory "openssl\html\man3" contains 3,848 files. I don't think it is necessory to keep so many doc files in GCC release.

(3) Totally,  there are 2,829 ".pyc" files. I don't think all these files are absolutely necessary to GCC. So I deleted all of them,  then run GCC and GDB once,  and found that 64 ".pyc" files generated automatically. I guess,  only those 64 ".pyc" files are necessory to GCC release. 

Totally,  if I compress ".\opt\lib\terminfo\" and ".\opt\share\", and delete unnecessory ".pyc" files,  the total amount files of GCC release will drop to about 5860 files. 

My suggestion is to decrease files in GCC release by removing unnecessory files. At least,  the directory of .\opt\share\doc which contains 3,994 files should be compressed or deleted.

**Comment by starg2** [comment]
(1) Do you know which one is actually necessary, `opt/lib/terminfo` or `opt/share/terminfo`?

(2) [We stopped bundling openssl docs.](https://github.com/niXman/mingw-builds/commit/d02f73aa887e5b7f08c360893208e11358b75669#diff-f100bbca3c7aad3ceaa2f65a5852d9bb9eb4020d8266f3004cb42189972e1a95L98-R100) There should be less than 100 files in `opt/share/doc` now.

(3) `*.pyc` files are cache and shouldn't be distributed. I'll make a PR to remove them.

**Comment by anbangli** [comment]
To my limited personal knowledge, Terminfo is a database used in Linux and maybe used by curses lib or vi.

I noticed there is some files in `opt\lib` with "ncurses" in their filename. So I guess  the directory `opt\lib\terminfo` maybe necessary to ncurses lib. 

In my opinion, directory `opt\share\terminfo` should be removed. 
Beside, I don't think ncurses lib is used widely, so directory `opt\lib\terminfo` may be removed, too.
