### ISSUE TITLE
GCC 12.1.0 with runtime v10

### ISSUE THREAD

**Issue by cristianadam** [niXman/mingw-builds-binaries#6]
Please tag a `12.1.0-rt_v10-rev0` release. https://github.com/niXman/mingw-builds already has the necessary patches.

**Comment by niXman** [comment]
done.

**Comment by cristianadam** [comment]
Unfortunately all the sjlj jobs failed due to lack of diskspace. 😞 

One solution would be to delete the build directory after installation.

**Comment by cristianadam** [comment]
I think a `*-rev1` tag would be required since a change in `mingw-builds` is also needed.

I don't know what happened, either gcc 12.1 has way bigger binary directory for sjlj or the github action windows hosts got a disk reduction.

**Comment by niXman** [comment]
done.
