### ISSUE TITLE
Gfortran DLL missing

### ISSUE THREAD

**Issue by GasinAn** [niXman/mingw-builds-binaries#60]
After I compiled and used powershell to run Fortran "Hello world" program, it could run but nothing printed in screen. If I use cmd instead of powershell, everything became OK.
I found that comparing to MSYS2 bin directory, some DLL is missing in mingw64\bin. I tried copy every DLL in MSYS2 bin directory (see my repo [mingw64_gfortran_dll](https://github.com/GasinAn/mingw64_gfortran_dll)) to mingw64\bin, and then I found that everything became OK in powershell.

**Comment by niXman** [comment]
hi,

it would be better if you could determine which exactly DLLs are really needed.
we can't just put a couple of DLLs into our distro...

**Comment by GasinAn** [comment]
I know what happens! There is no other DLL needed. The only problem is that libgfortran-5.dll doesn‘t work well.

**Comment by niXman** [comment]
hmm...

**Comment by starg2** [comment]
This sounds like a dll hell again.

@GasinAn Try running `cmd /c where libgfortran-5.dll` on both cmd and powershell and compare the results.

**Comment by GasinAn** [comment]
@starg2 Both are [my mingw64 path]\bin\libgfortran-5.dll.

**Comment by GasinAn** [comment]
@starg2 Now the situation is that, if I replace mingw-builds-binaries libgfortran-5.dll with libgfortran-5.dll copied from MSYS2, my problem will be immediately solved ("Hello world" will be printed in screen). Therefore in my opinion, there is something wrong in mingw-builds-binaries libgfortran-5.dll, but I don't know what is wrong.

**Comment by starg2** [comment]
I see. Maybe some of patches in https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gcc will help?

Have you tried running it under a debugger?

**Comment by nenin-sc** [comment]
> @starg2 Now the situation is that, if I replace mingw-builds-binaries libgfortran-5.dll with libgfortran-5.dll copied from MSYS2, my problem will be immediately solved ("Hello world" will be printed in screen). Therefore in my opinion, there is something wrong in mingw-builds-binaries libgfortran-5.dll, but I don't know what is wrong.

I have observation, that in the situation when dll and  application were linked with different version of the crt- one with msvcrt and the other with  ucrt - strange things may happens.

**Comment by niXman** [comment]
@GasinAn any progress on this?
if the question is solved - please close the issue.

**Comment by GasinAn** [comment]
@niXman Sorry, the problem has not been solved, although I'm not in hurry because I can 'solve' it by using clumsy method mentioned before (also method 1 mentioned below). You can close this issue if you are willing to.

Here I re-report what I have found: In my Windows 11 (I recently updated my system, when I opened this issue it was Windows 10) 64 bit system, if I add 'mingw64/bin' to PATH, write fortran 'hello world' program, compile it to a.exe and run a.exe in Powershell, nothing will be printed (in CMD there will be no problem). This can be solved by one of following methods:

1. replace libgfortran-5.dll by [msys2 libgfortran-5.dll](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-gcc-libgfortran?repo=ucrt64).

2. copy mingw-builds-binaries libgfortran-5.dll and libgcc_s_seh-1.dll, and paste them to directory containing a.exe.

Thank you!

**Comment by GasinAn** [comment]
@niXman Thank you so much! I run 'gfortran -v' in Msys2 and find that it uses 'posix' thread model. I used 'win32' version before. Now I download 'posix' version of mingw-builds-binaries, and I find that it doesn't have the problem I said! If it is my fault, I am so sorry.
Now I close this issue.
