### ISSUE TITLE
Mingw32

### ISSUE THREAD

**Issue by Carluccio** [niXman/mingw-builds-binaries#63]
I have windows 10 and I installed mingw32 https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev1/i686-13.2.0-release-posix-dwarf-msvcrt-rt_v11 -rev1.7z
It compiles the program perfectly, but doesn't run it.

**Comment by nenin-sc** [comment]
> but doesn't run it.

What do you mean? run time error?

**Comment by Carluccio** [comment]
Resolved!! I didn't put the -static option
