### ISSUE TITLE
Threads don't work with the posix version...

### ISSUE THREAD

**Issue by Paulo-D2000** [niXman/mingw-builds-binaries#64]
I get the errors when compiling anything that uses threads... 
```
C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++/bits/std_thread.h: In function 'bool std::operator==(thread::id, thread::id)':
C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++/bits/std_thread.h:330:26: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' and 'std::thread::native_handle_type')
  330 |     return __x._M_thread == __y._M_thread;
      |            ~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~
      |                |                |
      |                |                std::thread::native_handle_type
      |                std::thread::native_handle_type
```
and 
```
C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++/thread: In function 'bool std::operator<(thread::id, thread::id)':
C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++/thread:79:26: error: no match for 'operator<' (operand types are 'std::thread::native_handle_type' and 'std::thread::native_handle_type')
   79 |     return __x._M_thread < __y._M_thread;
      |            ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
      |                |               |
      |                |               std::thread::native_handle_type
      |                std::thread::native_handle_type
````

**Comment by niXman** [comment]
please provide minimal code that demonstrates the problem.
and the compiler flags too.

**Comment by Paulo-D2000** [comment]
I was trying to compile https://github.com/luigifcruz/CyberEther on windows using the static build... It was building libSoapyAirspy with the command ```FAILED: subprojects/SoapyAirspy-soapy-airspy-0.2.0/libSoapyAirspy.a.p/Streaming.cpp.obj
"x86_64-w64-mingw32-g++" "-Isubprojects\SoapyAirspy-soapy-airspy-0.2.0\libSoapyAirspy.a.p" "-Isubprojects\SoapyAirspy-soapy-airspy-0.2.0" "-I..\subprojects\SoapyAirspy-soapy-airspy-0.2.0" "-I..\subprojects\airspyone_host-1.0.10\libairspy\src" "-I..\subprojects\libusb-1.0.26\libusb" "-I..\subprojects\libusb-1.0.26\libusb\os" "-IC:/Users/Vitor/miniforge3/envs/gnuradio/Library/include" "-fdiagnostics-color=always" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c++11" "-O3" "-DNOMINMAX" "/MP" "/wd4251" "/wd4503" "-DSTRERROR_R_XSI" -MD -MQ subprojects/SoapyAirspy-soapy-airspy-0.2.0/libSoapyAirspy.a.p/Streaming.cpp.obj -MF "subprojects\SoapyAirspy-soapy-airspy-0.2.0\libSoapyAirspy.a.p\Streaming.cpp.obj.d" -o subprojects/SoapyAirspy-soapy-airspy-0.2.0/libSoapyAirspy.a.p/Streaming.cpp.obj "-c" ../subprojects/SoapyAirspy-soapy-airspy-0.2.0/Streaming.cpp```

**Comment by niXman** [comment]
great, but please provide minimal code that demonstrates the problem.

**Comment by Paulo-D2000** [comment]
Oh, it was a  bug on my configuration... The command line tools were using headers from another threading lib... Sorry for the trouble
