### ISSUE TITLE
Update request: Include binutils 2.42

### ISSUE THREAD

**Issue by shueja** [niXman/mingw-builds-binaries#68]
Hello,
We currently use your binaries for our GitHub CI pipeline. We're running into linking issues that were fixed in binutils 2.40 (https://github.com/rust-lang/rust/issues/112368 for context). 
As binutils 2.39 is over a year and a half old at this point, is it possible to get a binary release here that includes a newer version of binutils?

Thank you.

**Comment by starg2** [comment]
There is already a PR to update binutils to 2.42: niXman/mingw-builds#669. You can download the corresponding CI artifacts [here](https://github.com/starg2/mingw-builds/actions/runs/7754190255).

Hopefully the PR will get merged soon.

**Comment by oltolm** [comment]
This can be closed.
