### ISSUE TITLE
We need SEH that conforms to Microsoft's specific extensions

### ISSUE THREAD

**Issue by lvyitianshi** [niXman/mingw-builds-binaries#74]
I'm a novice programmer, so some of my words might be silly. I've been looking for __try, __except, __finally,__leave in mingw， they use the same usage as Microsoft specific extensions, but there are only __try1 and __except1 in mingw, and it has a very different syntax from __try and __except, and I can't learn and use seh by looking at Microsoft official documentation. We should keep __try1 and __except1, but also have the same __try,__except, __finally,__leave that use Microsoft specific extensions. Thanks :)

**Comment by niXman** [comment]
as you pointed out above - these are Microsoft specific extensions, and I don't think anyone will waste time implementing these non-standard features.

but if you implement it and send me a patch - I'll apply it.
thanks!

**Comment by lvyitianshi** [comment]
Thanks for your reply, but I'm sorry, I don't have the ability to implement it at the moment, I'm only going to use C for now, __try and __except and others that may need to use assembly, because its implementation requires modifying the cpu registers, but I'll try my best to learn it, wouldn't it be cool to be able to catch hardware exceptions?

If there's nothing going on, I'll close the conversation.

Have a good day :)

**Comment by niXman** [comment]
> wouldn't it be cool to be able to catch hardware exceptions?

What is `hardware exceptions`?
