### ISSUE TITLE
Please build win32-sjlj

### ISSUE THREAD

**Issue by Mavigsm** [niXman/mingw-builds-binaries#76]
Please build i686-14.1.0-release-win32-sjlj

**Comment by niXman** [comment]
hi,

a few years ago we decided to stop build `SJLJ` builds because almost no one uses builds with `SJLJ` exceptions these days.
do you have any reason to use SJLJ builds? why don't you use builds with `SEH` or `DWARF` exceptions?

**Comment by Mavigsm** [comment]
I use libraries created with MSVC, sjlj is more compatible

**Comment by Mavigsm** [comment]
currently i am using i686-12.2.0-release-win32-sjlj-rt_v10-rev0, please include win32-sjlj in current versions

**Comment by niXman** [comment]
> I use libraries created with MSVC, sjlj is more compatible

but MSVC compiler uses SEH =)

**Comment by nenin-sc** [comment]
> exceptions and SEH, but not a word about SJLJ.

Looks like SJLJ can somehow path through pieces of the code with SEH, and DWARFs have problem with it. But as far as I understood it is necessary to have such execution path SJLJ -> SEH->SJLJ, which for me looks quit exotic.

**Comment by starg2** [comment]
Well, you can always build it yourself.

**Comment by Mavigsm** [comment]
> Well, you can always build it yourself.

I can't do this please give win32-sjlj support
