### ISSUE TITLE
Which one to choose?

### ISSUE THREAD

**Issue by Willaaaaaaa** [niXman/mingw-builds-binaries#77]
As a beginner in programming, I can't distinguish the differences between each version. Could you please tell me the exact meaning of each file means? I don't know which zip should I download.

**Comment by nenin-sc** [comment]
1. Which OS you have: Win 11, Win 10, Win 7, Win XP?
2. Is it 32b or 64b?

**Comment by quantumtino** [comment]
win 11 64b,thank you!
