### ISSUE TITLE
Can it be installed to USB drive?

### ISSUE THREAD

**Issue by t1m013y** [niXman/mingw-builds-binaries#86]
I want to install it on my USB drive to always have it with me. Can I just unpack mingw to my USB drive? Will it use/modify any local files/registry?

**Comment by nenin-sc** [comment]
Very likely you can, but it requires a PATH aimed on _bin_ folder. 
Apropos, it may be slow....

**Comment by t1m013y** [comment]
> it requires a PATH aimed on _bin_ folder

A have bat script that automatically sets `PATH` on my USB drive

> Apropos, it may be slow

USB 3.0
