### ISSUE TITLE
binary_op' cannot be used as a function

### ISSUE THREAD

**Issue by magicse** [niXman/mingw-builds-binaries#9]
WinGW-W64 version x86_64-12.1.0-release-posix-seh-rt_v10-rev3
When compiling OPENCV I get next error 

:/mingw64/lib/gcc/x86_64-w64-mingw32/12.1.0/include/c++/numeric:298:38: error:
__binary_op' cannot be used as a function
 298 |                 *__init = __binary_op(*__init, *__first);
     |                           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~

**Comment by niXman** [comment]
hi,

I'm sure this bug is not related to MinGW...

**Comment by magicse** [comment]
Hi I know already. I found solve
Solution:
set -DWIN32 FOR OPENCV

**Comment by niXman** [comment]
great, then please close this issue.
